### ISSUE TITLE
TypeError in Chrome 28

### ISSUE THREAD

**Issue by dysbulic** [jinroh/kadoh#62]
I go through the following steps to get KadOH up and running on Ubuntu 12.04:
- `wget http://nodejs.org/dist/v0.10.12/node-v0.10.12.tar.gz # needed for browserify`
- `cd node-v0.10.12/`
- `./configure`
- `make`
- `sudo make install`
- `git clone https://github.com/jinroh/kadoh.git`
- `cd kadoh/`
- `npm install nconf optimist colors multimeter klass ltx bncode mustache connect browserify tagify socket.io socket.io-client`
- `bin/dht udp.default`
- `jake run:udp`
- `chromium-browser http://localhost:8080`

Then I click the "Connect" button which changes to "Connected". Next I click "Join" which goes to "Joining..." and in the console I get `Uncaught TypeError: Cannot call method 'size' of undefined`.

The offending statement is: `iterfind._currentReduceResult.size()`. I get an error at the same place in Firefox 25.

**Comment by alexstrat** [comment]
Indeed 1ec243d38fe38ea50d2bfd42dc760b7c8e5f2e69 introduced that bug, I just corrected it.

BTW, you should use `npm install .` that installs modules with predefined versions (defined in  `package.json`) rather than `npm install blah blah` that installs latest versions (no warranty to work at first glance).

BTW2, I wrote https://gist.github.com/alexstrat/4069162 once that explains how to launch the UDP DHT like you tried.
